TRAIN:
  ENABLE: True
  DATASET: epicsound
  BATCH_SIZE: 32
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 1
  CHECKPOINT_EPOCH_RESET: True
  AUTO_RESUME: True
TENSORBOARD:
  ENABLE: False
DATA:
  INPUT_CHANNEL_NUM: [1]
AUDIO_DATA:
  CLIP_SECS: 2.08
  NUM_FRAMES: 416
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: ms_threeway_dw_bottleneck_transform
  TIME_STRIDES: [[1], [2], [2], [2]]
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
  TEMP_KERNEL_SIZES: [[[5]], [[21]], [[21]], [[21]], [[21]]]
  FREQ_KERNEL_SIZES: [[[7]], [[21]], [[21]], [[21]], [[21]]]
BN:
  USE_PRECISE_STATS: True
  FREEZE: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.001
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 20, 25]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 30
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: -1.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: [44,]
  ARCH: fast
  MODEL_NAME: AudioInceptionNeXt
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: False
  DATASET: epicsound
  BATCH_SIZE: 32
  NUM_ENSEMBLE_VIEWS: 5
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
EPICKITCHENS:
  TRAIN_PLUS_VAL: False
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
